exclude = [".git", ".history", ".venv"]
src = ["animal_fact_api"]

target-version = "py312"
line-length = 79

[lint]
select = [
    # flake8-bugbear
    "B",
    # pydocstyle
    "D",
    # pycodestyle
    "E", "W",
    # Pyflakes
    "F",
    # isort
    "I",
    # flake8-print
    "T20",
    # pyupgrade
    "UP"
]

[lint.per-file-ignores]
"**/tests/*" = ["D"]

[lint.pydocstyle]
convention = "pep257"
