AWSTemplateFormatVersion: "2010-09-09"
Description: To help me understand how eventbridge works
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - x86_64
    CodeUri: eventbus_learning

Resources:
  GetFactFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.get_fact.GetFactFunction
