name: Pipeline CI

on: push
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - name: Run tests
      run: just test-cov
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: reports/coverage.xml
        badge: true
        format: markdown
        output: both
    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - run: just lint

  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - run: just bandit

  # safety:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: cmb84scd/python-action@v1
  #   - uses: pyupio/safety-action@v1
  #     with:
  #       api-key: ${{ secrets.SAFETY_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [test, lint, bandit]
    steps:
    - uses: cmb84scd/python-action@v1
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install CDK
      run: npm install -g aws-cdk
    - name: Synthesize CDK
      run: cdk synth
