name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - name: Run tests
      run: just test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: 'reports/unit_test_report.xml'
        include_passed: true
        check_annotations: true
        detailed_summary: true

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - run: just lint

  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - run: just bandit

  safety:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
